/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
export namespace Components {
  interface ScaleBadge {
    /**
     * @default 'default'
     */
    color: string;
    /**
     * @default ''
     */
    label: string;
  }
}
declare global {
  interface HTMLScaleBadgeElement extends Components.ScaleBadge, HTMLStencilElement {}
  var HTMLScaleBadgeElement: {
    prototype: HTMLScaleBadgeElement;
    new (): HTMLScaleBadgeElement;
  };
  interface HTMLElementTagNameMap {
    'scale-badge': HTMLScaleBadgeElement;
  }
}
declare namespace LocalJSX {
  interface ScaleBadge {
    /**
     * @default 'default'
     */
    color?: string;
    /**
     * @default ''
     */
    label?: string;
  }

  interface ScaleBadgeAttributes {
    label: string;
    color: string;
  }

  interface IntrinsicElements {
    'scale-badge': Omit<ScaleBadge, keyof ScaleBadgeAttributes> & {
      [K in keyof ScaleBadge & keyof ScaleBadgeAttributes]?: ScaleBadge[K];
    } & {
      [K in keyof ScaleBadge & keyof ScaleBadgeAttributes as `attr:${K}`]?: ScaleBadgeAttributes[K];
    } & { [K in keyof ScaleBadge & keyof ScaleBadgeAttributes as `prop:${K}`]?: ScaleBadge[K] };
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'scale-badge': LocalJSX.IntrinsicElements['scale-badge'] &
        JSXBase.HTMLAttributes<HTMLScaleBadgeElement>;
    }
  }
}
